[tool.poetry]
name = "fafi"
version = "0.1.5"
description = "CLI for indexing Firefox bookmarks."
authors = ["Sander van Dragt <sander@vandragt.com>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
newspaper3k = "^0.2.8"
click = "^7.1.1"
appdirs = "^1.4.3"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
fafi = 'fafi.fafi:cli'
